version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "UTC"
    reviewers:
      - Shopify/client-libraries-atc
    labels:
      - "Bundler upgrades"
    open-pull-requests-limit: 100
